@extends('admin.layout')

@section('admin-title') Prize Keys @endsection

@section('admin-content')
{!! breadcrumbs(['Admin Panel' => 'admin', 'Prize Keys' => 'admin/prizes']) !!}

<h1>Prize Keys</h1>

<p>Prize keys can be used to grant a user specified items when inputted.</p>

<div class="text-right mb-3"> 
    <a class="btn btn-primary" href="{{ url('admin/prizecodes/create') }}"><i class="fas fa-plus"></i> Create New Key</a>
</div>

@if(!count($prizes))
    <p>No prizes found.</p>
@else
    {!! $prizes->render() !!}
      <div class="row ml-md-2">
        <div class="d-flex row flex-wrap col-12 pb-1 px-0 ubt-bottom">
          <div class="col-6 col-md-2 font-weight-bold">Code</div>
          <div class="col-6 col-md-2 font-weight-bold">Generated by</div> 
          <div class="col-6 col-md-3 font-weight-bold"> </div>
        </div>
        @foreach($prizes as $prize)
        <div class="d-flex row flex-wrap col-12 mt-1 pt-1 px-0 ubt-top">
          <div class="col-6 col-md-2">{{ $prize->code }}</div>
          <div class="col-6 col-md-2">{!! $prize->user->displayName !!}</div> 
          <div class="col-6 col-md-1 text-right">
            <a href="{{ url('admin/prizecodes/edit/'.$prize->id) }}"  class="btn btn-primary py-0 px-2">Edit</a>
          </div>
        </div>
        @endforeach
      </div>

    {!! $prizes->render() !!}
    <div class="text-center mt-4 small text-muted">{{ $prizes->total() }} result{{ $prizes->total() == 1 ? '' : 's' }} found.</div>
@endif

@endsection
